# completions
autoload -Uz compinit
compinit -u

bindkey "''${key[Up]}" up-line-or-search

# Completion for kitty
# kitty + complete setup zsh | source /dev/stdin

# Direnv Hook
eval "$(direnv hook zsh)"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi
