# Extra ZSH config
rusb(){
  udisksctl power-off -b $1
}

mountu() {
  sudo mount -o gid=$GID,uid=$UID $1 $2
}

reload-keys(){
  ssh-add -D
  case $1 in
    "dev")
      git config --global user.email "marcos.schonfinkel@protonmail.com"
      git config --global user.name "Marcos Benevides"
      ssh-add "$HOME/.ssh/gitlab"
      ssh-add "$HOME/.ssh/github"
      ;;
    "work")
      git config --global user.email "marcos.benevides@datarisk.io"
      git config --global user.name "Marcos Benevides"
      ssh-add "$HOME/.ssh/work"
      ;;
    *)
      echo "invalid option"
      ;;
  esac
}

# completions
autoload -Uz compinit
compinit

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# Direnv Hook
eval "$(direnv hook zsh)"
